from backend.models.nhanvien import NhanVien
from backend.models.khachhang import KhachHang
from backend.models.sanpham import SanPham
from backend.models.nhomhang import NhomHang
from backend.models.hoadon import HoaDon
from backend.models.chitiethoadon import ChiTietHoaDon
from backend.models.khuyenmai import KhuyenMai
from backend.models.ap_dung_km import ApDungKM
from backend.models.phuongthuctt import PhuongThucTT
from backend.models.nhacungcap import NhaCungCap
from backend.models.phieunhap import PhieuNhap
from backend.models.chitietphieunhap import ChiTietPhieuNhap
from backend.models.lichsudiem import LichSuDiem
